### ISSUE TITLE
How to Manually invoke the DSDL compiler ?

### ISSUE THREAD

**Issue by SSSnow** [UAVCAN/libuavcan_stm32#4]
Manually invoke the DSDL compiler and add the output directory to the project includes

**Comment by pavel-kirienko** [comment]
See https://uavcan.org/Implementations/Libuavcan/Tutorials/8._Custom_data_types and https://github.com/UAVCAN/libuavcan/blob/master/libuavcan/dsdl_compiler/libuavcan_dsdlc. Run `libuavcan_dsdlc` with `--help` to get the usage info.

**Comment by SSSnow** [comment]
i will try, thx :)
